# Generated by Django 5.2 on 2025-07-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_add_like_bookmark_models'),
        ('articles', '0003_articlelike_bookmarkedarticle'),
    ]

    operations = [
    ]
